### ISSUE TITLE
Error: Could not find tools necessary to compile a package

### ISSUE THREAD

**Issue by Olaris** [rehbergT/zeroSum#1]
Hi,

When I tried to install package from github, RStudio prompted a message to install additional tools. And it directed to a [web page](https://www.cnet.com/how-to/install-command-line-developer-tools-in-os-x/) to install command line tools, which I already installed. 

Do you know what could possibly causing this error? 

Thanks!
```
> devtools::install_github("rehbergT/zeroSum/zeroSum")
Downloading GitHub repo rehbergT/zeroSum@master
Error: Could not find tools necessary to compile a package
```
```
> R.Version()

$platform
[1] "x86_64-apple-darwin15.6.0"


$arch
[1] "x86_64"

$os
[1] "darwin15.6.0"

$system
[1] "x86_64, darwin15.6.0"

$status
[1] ""

$major
[1] "3"

$minor
[1] "5.3"

$year
[1] "2019"

$month
[1] "03"

$day
[1] "11"

$`svn rev`
[1] "76217"

$language
[1] "R"

$version.string
[1] "R version 3.5.3 (2019-03-11)"

$nickname
[1] "Great Truth"
```

```
> system("clang --version")
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by rehbergT** [comment]
Hi, sry for the late response. I was not able to reproduce your issue :/ Maybe this is due to a devtools issue or a missing path variable in RStudio. Have you tried installing the zeroSum_2.0.3.tar.gz file manually from command line with "R CMD INSTALL zeroSum_2.0.3.tar.gz"?

**Comment by Olaris** [comment]
Thanks for the reply! I tried to used the source package to install but failed.
I think the problem is from my devtools, not from the package.
Here is the error code
```
clang-4.0: error: unable to execute command: Executable "ld" doesn't exist!
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [zeroSum.so] Error 1
ERROR: compilation failed for package ‘zeroSum’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/zeroSum’
```

Thanks for the help again! I will try to find solutions somewhere else.
