### ISSUE TITLE
Code Compilation Error on MacOS

### ISSUE THREAD

**Issue by DarioS** [rehbergT/zeroSum#2]
Unable to install on MacOS. Tried Deblain Linux and was successful. Perhaps it's time to turn on GitHub Actions and `R CMD check`?

**Comment by rehbergT** [comment]
Hi,
thanks for bringing this to my attention. However, It would have been even more helpful if you would have provided the error message encountered during installation, along with details about your hardware setup.

Previously, GitHub Actions (formerly Travis CI) was successfully building on macOS. However, upon your report, I initiated a new CI run and encountered the issue you mentioned. ZeroSum heavily utilizes AVX instructions, making it incompatible with ARM-based Mac hardware, which lacks support for these instructions.

To address this, it's possible to implement fallback code for AVX functions. The challenge lies in implementing compile-time logic to determine the platform architecture and select the appropriate code path. Specifically, utilizing `__APPLE__` and `__arm64__` defines to enable fallback code on ARM while retaining optimized AVX versions for x86.
An ideal solution involves extending AVX-optimized kernels to also support NEON instructions on ARM platforms. 

Unfortunately, I currently lack access to Apple Silicon hardware and have limited resources as this project is maintained in my spare time.

**Comment by DarioS** [comment]
Ah, I understand. Perhaps a sentence in README.md would help clarify which hardware it will not work on.

**Comment by rehbergT** [comment]
I totally forgot that I’ve already added fallback code. I've now added compile-time logic that should enable it to work on apple hardware. Could you please test it and let me know if it resolves the issue?

**Comment by DarioS** [comment]
Installation successful.
